-- ============================================================
-- TEASERFLIX — Schema completo con RLS y funciones de recomendación
-- Ejecutar en el SQL Editor de Supabase
-- ============================================================

-- ─── 1. TABLA DE PERFILES ────────────────────────────────────
-- Se vincula automáticamente al Auth de Supabase via trigger
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique,
  avatar_url text,
  full_name text,
  preferred_genres int[],        -- IDs de géneros TMDB: [28, 12]
  preferred_providers int[],     -- IDs de plataformas TMDB: [8, 337]
  has_completed_onboarding boolean default false,
  updated_at timestamp with time zone default now()
);

alter table profiles enable row level security;

create policy "profiles_select_own" on profiles
  for select to authenticated using (auth.uid() = id);

create policy "profiles_insert_own" on profiles
  for insert to authenticated with check (auth.uid() = id);

create policy "profiles_update_own" on profiles
  for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);


-- ─── 2. TABLA DE INTERACCIONES ───────────────────────────────
-- Núcleo del algoritmo: registra cómo el usuario se comporta con cada película
create table if not exists interactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  movie_id bigint not null,
  genre_ids int[] not null default '{}',  -- Géneros TMDB de la película
  watch_time int not null default 0,      -- Segundos reales vistos
  is_full_watch boolean not null default false,  -- ¿Vio el tráiler completo?
  is_fast_scroll boolean not null default false, -- ¿Pasó en menos de 2 s?
  is_interested boolean not null default false,  -- ¿Le dio like / watchlist?
  created_at timestamp with time zone default now() not null
);

alter table interactions enable row level security;

create policy "interactions_select_own" on interactions
  for select to authenticated using (auth.uid() = user_id);

create policy "interactions_insert_own" on interactions
  for insert to authenticated with check (auth.uid() = user_id);

create policy "interactions_update_own" on interactions
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- ─── 3. TABLA DE LIKES ───────────────────────────────────────
create table if not exists likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  movie_id bigint not null,
  created_at timestamp with time zone default now() not null,
  unique(user_id, movie_id)
);

alter table likes enable row level security;

create policy "likes_select_own" on likes
  for select to authenticated using (auth.uid() = user_id);

create policy "likes_insert_own" on likes
  for insert to authenticated with check (auth.uid() = user_id);

create policy "likes_delete_own" on likes
  for delete to authenticated using (auth.uid() = user_id);


-- ─── 4. TABLA DE WATCHLIST ───────────────────────────────────
create table if not exists watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  movie_id bigint not null,
  created_at timestamp with time zone default now() not null,
  unique(user_id, movie_id)
);

alter table watchlist enable row level security;

create policy "watchlist_select_own" on watchlist
  for select to authenticated using (auth.uid() = user_id);

create policy "watchlist_insert_own" on watchlist
  for insert to authenticated with check (auth.uid() = user_id);

create policy "watchlist_delete_own" on watchlist
  for delete to authenticated using (auth.uid() = user_id);


-- ─── 5. TABLA DE AMIGOS (SEGUIMIENTO) ───────────────────────
create table if not exists friends (
  id bigint generated by default as identity primary key,
  follower_id uuid references auth.users on delete cascade not null,
  following_id uuid references auth.users on delete cascade not null,
  created_at timestamp with time zone default now() not null,
  unique(follower_id, following_id)
);

alter table friends enable row level security;

create policy "friends_select_any" on friends
  for select to authenticated using (true);

create policy "friends_insert_own" on friends
  for insert to authenticated with check (auth.uid() = follower_id);

create policy "friends_delete_own" on friends
  for delete to authenticated using (auth.uid() = follower_id);


-- ============================================================
-- FUNCIONES DE RECOMENDACIÓN
-- ============================================================

-- ─── A. Géneros preferidos del usuario (ponderados) ──────────
-- Puntaje: like/watchlist=15, tráiler completo=8, >60s=5, >30s=3, >10s=1, scroll rápido=-5
create or replace function get_user_genre_preferences(user_uuid uuid)
returns table (genre_id int, score bigint) as $$
begin
  return query
  select
    unnest(genre_ids) as genre_id,
    sum(
      case
        when is_interested then 15
        when is_full_watch then 8
        when is_fast_scroll then -5
        when watch_time >= 60 then 5
        when watch_time >= 30 then 3
        when watch_time >= 10 then 1
        else 0
      end
    ) as total_score
  from interactions
  where user_id = user_uuid
    and created_at > now() - interval '60 days'
  group by genre_id
  having sum(
    case
      when is_interested then 15
      when is_full_watch then 8
      when is_fast_scroll then -5
      when watch_time >= 60 then 5
      when watch_time >= 30 then 3
      when watch_time >= 10 then 1
      else 0
    end
  ) > 0
  order by total_score desc;
end;
$$ language plpgsql security definer;


-- ─── B. Top N género IDs recomendados (para llamar desde cliente) ─
create or replace function get_recommended_genre_ids(
  user_uuid uuid,
  top_n int default 5,
  lookback_days int default 60
)
returns int[] as $$
declare
  result int[];
begin
  select array(
    select genre_id
    from (
      select
        unnest(genre_ids) as genre_id,
        sum(
          case
            when is_interested then 15
            when is_full_watch then 8
            when is_fast_scroll then -5
            when watch_time >= 60 then 5
            when watch_time >= 30 then 3
            when watch_time >= 10 then 1
            else 0
          end
        ) as score
      from interactions
      where user_id = user_uuid
        and created_at > now() - (lookback_days || ' days')::interval
      group by genre_id
    ) sub
    where score > 0
    order by score desc
    limit top_n
  ) into result;

  return coalesce(result, array[]::int[]);
end;
$$ language plpgsql security definer;


-- ─── C. IDs de películas ya vistas (para excluir del feed) ───
create or replace function get_seen_movie_ids(
  user_uuid uuid,
  limit_n int default 500
)
returns bigint[] as $$
  select array(
    select distinct movie_id
    from interactions
    where user_id = user_uuid
    order by movie_id
    limit limit_n
  );
$$ language sql security definer;


-- ============================================================
-- TRIGGER: crear perfil al registrar usuario
-- ============================================================

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
